export const SET_USER = "SET_USER";
export const SET_USER_IMAGE_URL = "SET_USER_IMAGE_URL";
export const REMOVE_USER = "REMOVE_USER";
export const SET_RESTAURANT = "SET_RESTAURANT";
export const SET_RESTAURANT_IMAGE_URL = "SET_RESTAURANT_IMAGE_URL";
export const SET_RESTAURANT_LARGE_IMAGE_URL = "SET_RESTAURANT_LARGE_IMAGE_URL";
export const REMOVE_RESTAURANT = "REMOVE_RESTAURANT";
